version: '3.1'

services:
  question-bank-app:
    image: julioborges05/question-bank-app
    ports:
      - 8080:8080
    depends_on:
      - question-bank-db

  question-bank-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=question-bank-db
      - POSTGRES_USER=quarkus
      - POSTGRES_PASSWORD=quarkus